Small changes
MikeWooster/api-client pull request #53
Opened 2021-01-16 00:48 UTC by mom1

- Improve README.md
- wraps for paginated decorator

This is needed for api-client-pydantic to work.

After the release of these changes, I can make the first release of the package [api-client-pydantic](https://github.com/mom1/api-client-pydantic)

2021-01-16 14:03 UTC, MikeWooster requested changes
just a small change for the readme.

2021-01-16 14:12 UTC, mom1 commented on README.md
> +11. [Pydantic requests/responses](#Pydantic)
Do I need to return this section?

2021-01-16 14:57 UTC, MikeWooster commented on README.md
> +11. [Pydantic requests/responses](#Pydantic)
there's no Pydantic section in the readme.  Probably best to remove this, or change it to an `Extensions` section where we can put the jsonmarshal/pydantic stuff.

2021-01-16 15:04 UTC, MikeWooster approved these changes

2021-01-16 15:04 UTC, MikeWooster commented
would you mind fixing up your commits into a single commit for me before this is merged?

2021-01-16 15:25 UTC, mom1 commented on README.md
> +11. [Pydantic requests/responses](#Pydantic)
Done

2021-01-16 15:26 UTC, mom1 commented
> would you mind fixing up your commits into a single commit for me before this is merged?

Done

2021-01-17 13:40 UTC, MikeWooster approved these changes

2021-01-17 13:40 UTC, merged